"""Generate Python TypedDict stubs from JSON schemas."""

from typing import Any, Dict


def _json_type_to_python(json_type: Any) -> str:
    """Convert JSON schema type to Python type."""
    if isinstance(json_type, list):
        # Union type like ['string', 'null']
        types = [_json_type_to_python(t) for t in json_type]
        return f"Union[{', '.join(types)}]"

    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "List",
        "object": "Dict[str, Any]",
        "null": "None",
    }
    return type_map.get(json_type, "Any")


def _generate_class_name(name: str) -> str:
    """Generate PascalCase class name from snake_case."""
    return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))


def _generate_field_type(prop: Dict[str, Any], required: bool) -> str:
    """Generate type annotation for a field."""
    json_type = prop.get("type", "object")

    if json_type == "array":
        items = prop.get("items", {})
        item_type = _json_type_to_python(items.get("type", "Any"))
        base_type = f"List[{item_type}]"
    elif json_type == "object":
        base_type = "Dict[str, Any]"
    else:
        base_type = _json_type_to_python(json_type)

    # Add NotRequired if not required
    if not required:
        return f"NotRequired[{base_type}]"
    return base_type


def generate_typed_dict(schema: Dict[str, Any], class_name: str) -> str:
    """
    Generate TypedDict class from JSON schema.

    Args:
        schema: JSON schema dictionary
        class_name: Name for the TypedDict class

    Returns:
        Python code as string
    """
    properties = schema.get("properties", {})
    required_fields = set(schema.get("required", []))

    # Check if any field has special characters
    has_special_chars = any(
        "-" in name or not name.isidentifier() for name in properties.keys()
    )

    if has_special_chars:
        # Use functional syntax for TypedDict
        lines = [
            "from typing import Any, Dict, List, NotRequired, TypedDict, Union",
            "",
            "",
            f"{class_name} = TypedDict(",
            f'    "{class_name}",',
            "    {",
        ]

        for field_name, prop in properties.items():
            is_required = field_name in required_fields
            field_type = _generate_field_type(prop, is_required)
            lines.append(f'        "{field_name}": {field_type},')

        lines.append("    },")
        lines.append(")")
    else:
        # Use class syntax
        lines = [
            "from typing import Any, Dict, List, NotRequired, TypedDict, Union",
            "",
            "",
            f"class {class_name}(TypedDict):",
            '    """Generated from JSON schema."""',
        ]

        if not properties:
            lines.append("    pass")
        else:
            for field_name, prop in properties.items():
                is_required = field_name in required_fields
                field_type = _generate_field_type(prop, is_required)
                lines.append(f"    {field_name}: {field_type}")

    return "\n".join(lines)


def generate_all_stubs(schemas: Dict[str, Dict[str, Any]]) -> str:
    """
    Generate TypedDict stubs for all schemas.

    Args:
        schemas: Dictionary mapping schema names to schemas

    Returns:
        Complete Python module as string
    """
    lines = [
        '"""Auto-generated TypedDict stubs from JSON schemas.',
        "",
        "DO NOT EDIT - Generated by scripts/generate_type_stubs.py",
        '"""',
        "",
        "from typing import Any, Dict, List, NotRequired, TypedDict, Union",
        "",
    ]

    for schema_name, schema in schemas.items():
        class_name = _generate_class_name(schema_name)

        # Generate main class
        stub = generate_typed_dict(schema, class_name)
        # Skip imports line since we have it at top
        stub_lines = stub.split("\n")[3:]
        lines.extend(stub_lines)
        lines.append("")

    return "\n".join(lines)
