"""Auto-generated TypedDict stubs from JSON schemas.

DO NOT EDIT - Generated by scripts/generate_type_stubs.py
"""

from typing import Any, Dict, List, NotRequired, TypedDict, Union


class Event(TypedDict):
    """Generated from JSON schema."""

    Chapter: str
    Event: Dict[str, Any]


Date = TypedDict(
    "Date",
    {
        "Event_Name": str,
        "EventID": str,
        "Sub-event_Name": str,
        "Sub-eventID": str,
        "Date_Mentions": List[Dict[str, Any]],
    },
)

Place = TypedDict(
    "Place",
    {
        "Event_Name": str,
        "EventID": str,
        "Sub-event_Name": str,
        "Sub-eventID": str,
        "Place_Mentions": List[Dict[str, Any]],
    },
)

Supplemental = TypedDict(
    "Supplemental",
    {
        "Event_Name": str,
        "EventID": str,
        "Sub-event_Name": str,
        "Sub-eventID": str,
        "Supplemental_Material": List[Dict[str, Any]],
    },
)


class People(TypedDict):
    """Generated from JSON schema."""

    people: List[Dict[str, Any]]


class PeopleGroups(TypedDict):
    """Generated from JSON schema."""

    groups: List[Dict[str, Any]]


class Equipment(TypedDict):
    """Generated from JSON schema."""

    equipment: List[Dict[str, Any]]


class Map(TypedDict):
    """Generated from JSON schema."""

    MapID: str


class Casualties(TypedDict):
    """Generated from JSON schema."""

    casualties: List[Any]
